# Generated by Django 5.1.1 on 2024-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
