# Generated by Django 5.1.1 on 2025-05-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expenses",
            name="notes",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
