# Generated by Django 5.1.1 on 2025-05-08 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_expenses_purchase_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="charge_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
