# Generated by Django 5.1.1 on 2025-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_alter_expenses_charge_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="purchase_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
