# Generated by Django 5.1.1 on 2025-05-08 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_alter_expenses_purchase_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="bussines_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="card",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="discount",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="purchase_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
