# Generated by Django 5.1.1 on 2025-05-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "expenses",
            "0006_alter_expenses_amount_alter_expenses_bussines_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="discount",
            field=models.TextField(blank=True, default=False, null=True),
        ),
    ]
