# Generated by Django 5.1.1 on 2025-05-11 22:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0007_alter_expenses_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="expenses",
            name="submit_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="expenses",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="expenses.category",
            ),
        ),
    ]
